=== folio-org/mod-users-keycloak/src/main/resources/swagger.api/schemas/user.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "User Schema",
  "description": "A user",
  "type": "object",
  "properties": {
    "username": {
      "description": "A unique name belonging to a user. Typically used for login",
      "type": "string"
    },
    "id": {
      "description" : "A globally unique (UUID) identifier for the user",
      "type": "string",
      "format": "uuid"
    },
    "externalSystemId": {
      "description": "A unique ID that corresponds to an external authority",
      "type": "string"
    },
    "barcode": {
      "description": "The unique library barcode for this user",
      "type": "string"
    },
    "active": {
      "description": "A flag to determine if the user's account is effective and not expired. The tenant configuration can require the user to be active for login. Active is different from the loan patron block",
      "type": "boolean"
    },
    "type": {
      "description": "The class of user like staff or patron; this is different from patronGroup",
      "type": "string"
    },
    "patronGroup": {
      "description": "A UUID corresponding to the group the user belongs to, see /groups API, example groups are undergraduate and faculty; loan rules, patron blocks, fees/fines and expiration days can use the patron group",
      "type": "string",
      "format": "uuid"
    },
    "departments": {
      "description": "A list of UUIDs corresponding to the departments the user belongs to, see /departments API",
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "format": "uuid"
      }
    },
    "meta": {
      "description": "Deprecated",
      "type": "object"
    },
    "proxyFor": {
      "description" : "Deprecated",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "personal": {
      "description": "Personal information about the user",
      "$ref": "personal.json"
    },
    "enrollmentDate": {
      "description": "The date in which the user joined the organization",
      "type": "string",
      "format": "date-time"
    },
    "expirationDate": {
      "description": "The date for when the user becomes inactive",
      "type": "string",
      "format": "date-time"
    },
    "createdDate": {
      "description": "Deprecated",
      "type": "string",
      "format": "date-time"
    },
    "updatedDate": {
      "description": "Deprecated",
      "type": "string",
      "format": "date-time"
    },
    "metadata": {
      "$ref": "common/metadata.json"
    },
    "tags": {
      "$ref": "common/tags.json"
    },
    "customFields" : {
      "description": "Object that contains custom field",
      "type": "object",
      "additionalProperties": true
    },
    "preferredEmailCommunication": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Support",
          "Programs",
          "Services"
        ]
      },
      "maxItems": 3,
      "uniqueItems": true,
      "description": "Preferred email communication types"
    },
    "loanAnonymizationPreference": {
      "description": "Preference for anonymizing the user's closed loans; a missing value means libraryPolicy",
      "type": "string",
      "enum": [
        "libraryPolicy",
        "asEarlyAsPossible",
        "never"
      ]
    }
  },
  "additionalProperties": false
}

=== folio-org/mod-users-keycloak/src/test/resources/json/user/create-user-no-lastname-request.json
{
  "username": "ZakirBailey",
  "id": "d3958402-2f80-421b-a527-9933245a3556",
  "barcode": "12359",
  "active": true,
  "type": "",
  "patronGroup": "503a81cd-6c26-400f-b620-14c08943697c",
  "personal": {
    "firstName": "Bailey",
    "middleName": "",
    "preferredFirstName": "",
    "email": "new9@new.com",
    "phone": "",
    "mobilePhone": "",
    "addresses": [],
    "preferredContactTypeIds": ["002"]
  },
  "enrollmentDate": "2020-10-07T04:00:00.000+00:00",
  "expirationDate": "2023-02-28T23:59:59.000+00:00"
}

=== folio-org/mod-users-keycloak/src/test/resources/json/user/create-user-no-id-request.json
{
  "username": "ZakirBailey",
  "barcode": "12359",
  "active": true,
  "type": "",
  "patronGroup": "503a81cd-6c26-400f-b620-14c08943697c",
  "personal": {
    "firstName": "Bailey",
    "lastName": "Zakir",
    "middleName": "",
    "preferredFirstName": "",
    "email": "new9@new.com",
    "phone": "",
    "mobilePhone": "",
    "addresses": [],
    "preferredContactTypeIds": ["002"]
  },
  "enrollmentDate": "2020-10-07T04:00:00.000+00:00",
  "expirationDate": "2023-02-28T23:59:59.000+00:00"
}

=== folio-org/mod-users-keycloak/src/test/resources/json/user/get-user-response.json
{
  "username": "ZakirBailey",
  "id": "d3958402-2f80-421b-a527-9933245a3556",
  "barcode": "12359",
  "active": true,
  "type": "",
  "patronGroup": "503a81cd-6c26-400f-b620-14c08943697c",
  "departments": [],
  "proxyFor": [],
  "personal": {
    "lastName": "Zakir",
    "firstName": "Bailey",
    "middleName": "",
    "preferredFirstName": "",
    "email": "new9@new.com",
    "phone": "",
    "mobilePhone": "",
    "addresses": [],
    "preferredContactTypeIds": ["002"],
    "profilePictureLink": "https://folio.org/profiles/picture.jpg"
  },
  "enrollmentDate": "2020-10-07T04:00:00.000Z",
  "expirationDate": "2023-02-28T23:59:59.000Z",
  "createdDate": "2023-02-06T11:16:48.700Z",
  "updatedDate": "2023-02-06T11:16:48.700Z",
  "metadata": {
    "createdDate": "2023-02-06T11:15:35.100Z",
    "updatedDate": "2023-02-06T11:16:48.685Z"
  },
  "customFields": {}
}

=== folio-org/mod-users-keycloak/src/test/resources/json/user/create-user-request.json
{
  "username": "create-user-auth-exist",
  "id": "d24b7b4a-00ed-416e-a810-981b003bd158",
  "barcode": "12359",
  "active": true,
  "type": "",
  "patronGroup": "503a81cd-6c26-400f-b620-14c08943697c",
  "personal": {
    "firstName": "Bailey",
    "lastName": "Zakir",
    "middleName": "",
    "preferredFirstName": "",
    "email": "au_exist@mail.com",
    "phone": "",
    "mobilePhone": "",
    "addresses": [],
    "preferredContactTypeIds": ["002"]
  },
  "enrollmentDate": "2020-10-07T04:00:00.000+00:00",
  "expirationDate": "2023-02-28T23:59:59.000+00:00"
}

=== folio-org/mod-users-keycloak/src/test/resources/json/user/create-user-unknown-group-request.json
{
  "username": "ZakirBailey",
  "id": "d3958402-2f80-421b-a527-9933245a3556",
  "barcode": "12359",
  "active": true,
  "type": "",
  "patronGroup": "af8ff160-8d4d-4190-bb18-c91dbe8b507b",
  "personal": {
    "lastName": "Zakir",
    "firstName": "Bailey",
    "middleName": "",
    "preferredFirstName": "",
    "email": "new9@new.com",
    "phone": "",
    "mobilePhone": "",
    "addresses": [],
    "preferredContactTypeIds": ["002"]
  },
  "enrollmentDate": "2020-10-07T04:00:00.000+00:00",
  "expirationDate": "2023-02-28T23:59:59.000+00:00"
}
